service: product-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  environment:
    pgConfig: ${s3:nodejs-aws-be-variables/pg-config}

plugins:
  - serverless-webpack

functions:
  getProductsList:
    handler: src/handlers/get-products-list.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
#          authorizer:
#            arn: arn:aws:cognito-idp:eu-west-1:583941112965:userpool/eu-west-1_pRzicT5x8

  getProductsById:
    handler: src/handlers/get-products.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true

  postProducts:
    handler: src/handlers/post-products.postProducts
    events:
      - http:
          path: /products
          method: post
          cors: true

resources:
  Resources:
    GatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
