openapi: 3.0.3
info:
  title: Product service
  version: v1.0.0
paths:
  /products:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Server error
          content:
            text/plain:
              schema:
                type: string
                example: Server error
  '/products/{productId}':
    get:
      parameters:
        - name: productId
          in: path
          description: User ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Not found
          content:
            text/plain:
              schema:
                type: string
                example: Product not found
        '500':
          description: Server error
          content:
            text/plain:
              schema:
                type: string
                example: Server error
components:
  schemas:
    Product:
      type: object
      properties:
        count:
          type: integer
          example: 4
        description:
          type: string
          example: Short Product Description
        id:
          type: string
          format: uuid
        price:
          type: number
          example: 2.4
        title:
          type: string
          example: ProductOne
      required:
        - id
        - title
