service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  environment:
    pgConfig: ${s3:nodejs-aws-be-variables/pg-config}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::${self:custom.filesBucketName}/${self:custom.uploadFolderName}/*
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::${self:custom.filesBucketName}/${self:custom.parsedFolderName}/*
        - Effect: Allow
          Action:
            - sqs:*
          Resource: !GetAtt CatalogItemsQueue.Arn
        - Effect: Allow
          Action:
            - sns:*
          Resource: !Ref CreateProductTopic

custom:
  filesBucketName: ${self:service}-${self:provider.stage}-files
  uploadFolderName: uploaded
  parsedFolderName: parsed

plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: src/handlers/import-products-file.importProductsFile
    environment:
      BUCKET_NAME: ${self:custom.filesBucketName}
      UPLOAD_FOLDER_NAME: ${self:custom.uploadFolderName}
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer:
            arn: ${cf:authorization-service-dev.BasicAuthorizerArn}

  importFileParser:
    handler: src/handlers/import-file-parser.importFileParser
    environment:
      CATALOG_ITEMS_QUEUE:
        Ref: CatalogItemsQueue
      BUCKET_NAME: ${self:custom.filesBucketName}
      PARSED_FOLDER_NAME: ${self:custom.parsedFolderName}
    events:
      - s3:
          bucket: ${self:custom.filesBucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:custom.uploadFolderName}
          existing: true

  catalogBatchProcess:
    handler: src/handlers/catalog-batch-process.catalogBatchProcess
    environment:
      CREATE_PRODUCT_TOPIC: !Ref CreateProductTopic
    events:
      - sqs:
          arn: !GetAtt CatalogItemsQueue.Arn
          batchSize: 5

resources:
  Resources:
    FilesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.filesBucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - 'PUT'
              AllowedOrigins:
                - '*'
              ExposedHeaders:
                - 'x-amz-server-side-encryption'
                - 'x-amz-request-id'
                - 'x-amz-id-2'
              MaxAge: 3000
    GatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    CatalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    CreateProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    CreateProductTopicSubscriptionTen:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: 'roman_shuvalov@epam.com'
        Protocol: email
        TopicArn: !Ref CreateProductTopic
        FilterPolicy:
          price: [10]
    CreateProductTopicSubscriptionFive:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: 'romanshuvalov@yahoo.com'
        Protocol: email
        TopicArn: !Ref CreateProductTopic
        FilterPolicy:
          price: [5]
